Avoid compilation error due to a maybe-uninitialized false-positive in GCC 12.2
tket/src/Circuit/CircUtils.cpp lines 1230 and 1237 clearly only deference the std::optional
within a checked branch. However, GCC 12.2 gives:

```
/build/tket/src/Circuit/CircUtils.cpp: In function 'std::tuple<tket::Circuit, std::array<SymEngine::Expression, 3>, tket::Circuit> tket::normalise_TK2_angles(Expr, Expr, Expr)':
/build/tket/src/Circuit/CircUtils.cpp:1237:13: error: '*(double*)((char*)&b_eval + offsetof(std::optional<double>,std::optional<double>::<unnamed>.std::_Optional_base<double, true, true>::<unnamed>))' may be used uninitialized [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wmaybe-uninitialized-Werror=maybe-uninitialized8;;]
 1237 |     *b_eval -= 3;
      |     ~~~~~~~~^~~~
/build/tket/src/Circuit/CircUtils.cpp:1148:25: note: '*(double*)((char*)&b_eval + offsetof(std::optional<double>,std::optional<double>::<unnamed>.std::_Optional_base<double, true, true>::<unnamed>))' was declared here
 1148 |   std::optional<double> b_eval = eval_expr_mod(b, 4);
      |                         ^~~~~~
/build/tket/src/Circuit/CircUtils.cpp:1230:13: error: '*(double*)((char*)&a_eval + offsetof(std::optional<double>,std::optional<double>::<unnamed>.std::_Optional_base<double, true, true>::<unnamed>))' may be used uninitialized [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wmaybe-uninitialized-Werror=maybe-uninitialized8;;]
 1230 |     *a_eval -= 3;
      |     ~~~~~~~~^~~~
/build/tket/src/Circuit/CircUtils.cpp:1147:25: note: '*(double*)((char*)&a_eval + offsetof(std::optional<double>,std::optional<double>::<unnamed>.std::_Optional_base<double, true, true>::<unnamed>))' was declared here
 1147 |   std::optional<double> a_eval = eval_expr_mod(a, 4);
```

An alternative fix is to apply a `#pragma GCC diagnostic ignore "-Wmaybe-uninitialized"` to the regions in question.